name: auto_spacer
version: 0.0.2
description: A simple package to add spaces between widgets
repository: https://github.com/chitkosarvesh/auto_spacer
environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
